export const SET_AUTH_STATE = 'AUTH/SET_AUTH_STATE';
export const SET_CURRENT_USER = 'AUTH/SET_CURRENT_USER';
export const SET_LOADING_STATUS = 'AUTH/SET_LOADING_STATUS';

// add chatRoom types
export const SET_CHAT_ROOM = 'CHAT/SET_CHAT_ROOM';

export const GET_CHATROOMS_REQUEST = 'GET_CHATROOMS_REQUEST';
export const GET_CHATROOMS_SUCCESS = 'GET_CHATROOMS_SUCCESS';
export const GET_CHATROOMS_FAILURE = 'GET_CHATROOMS_FAILURE';

export const UPDATE_CHATROOMS = 'UPDATE_CHATROOMS';